name: "syncer"
author: "GOG Nebula"
description: "Sync galaxy integration forks with upstream"
inputs:
  upstream:
    description: 'Upstream repo of the fork. (eg. Codertocat/Hello-World)'
    required: true
  upstream_ref: 
    description: 'The branch, tag or SHA to checkout (upstream).'
    default: ''
  reviewers:
    description: 'A comma or newline separated list of reviewers (GitHub usernames) to request a review from.'
runs:
  using: 'node16'
  main: 'dist/index.js'